①−4完成
kon2300/Practice1-4 pull request #1
Opened 2020-11-27 14:20 UTC by kon2300

2020-11-28 01:29 UTC, niganium reviewed
何点か指摘しました。修正したのち再提出をお願いいたします。

2020-11-28 01:29 UTC, niganium commented on index.js
> +let taskList = () => {
再代入がないのでconstになります

2020-11-28 01:29 UTC, niganium commented on index.js
> +let currentTask = [
再代入がないのでconstになります。再代入を必要としない場所にletをかけてしまうと意図しない箇所で再代入が発動して不具合が出る可能性があるのでできるだけconstを使用してください

2020-11-28 01:29 UTC, niganium commented on index.js
> +    console.log(i + ' : ' + '[内容]' + currentTask[i][0] + ',[ジャンル]' + currentTask[i][1]);
テンプレート文字列ですとシンプルになります
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals

2020-11-28 12:17 UTC, myzktkyk requested changes
レビューいたしました！何点か指摘があります。

2020-11-28 12:17 UTC, myzktkyk commented on index.js
> +];
Object の配列にした方が扱いやすいと思います。

```suggestion
const currentTask = [
  { content: '机を片付ける', genre : '掃除' },
  { content: '牛乳を買う', genre: '買い物' },
  { content: '散歩する', genre: '運動' }
]
```

2020-11-28 12:17 UTC, myzktkyk commented on index.js
> +  };
Object の配列にするとこんな感じで書き換えられます。

```suggestion
  currentTask.forEach((task, index) => {
    console.log(`${index} : [内容] ${task.content},[ジャンル] ${task.genre}`);
  });
```

2020-11-28 12:17 UTC, myzktkyk commented on index.js
> +currentTask.push([newTask, newGenre]);
Object の配列に Object を追加する場合は以下のようにします。

```suggestion
currentTask.push({ content: newTask, genre: newGenre });
```

2020-11-29 01:51 UTC, niganium commented
問題ありません！
引き続き後続の作業をお願いいたします！

2021-01-08 11:05 UTC, merged